services:
  express:
    image: ghcr.io/alexispet/final-test-alice-aa-a/express:main
#      context: .
#      #      choose image : next
#      target: express
    environment:
      #      stable or unstable
      NODE_ENV: development
      DB_HOST: db
      DB_USER: expressuser
      DB_PASSWORD: expresspassword
      DB_DATABASE: expressdb
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ".:/app"
  db:
    image: mariadb:11.2.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: expressdb
      MYSQL_USER: expressuser
      MYSQL_PASSWORD: expresspassword
#    volumes:
#      - "./docker/mariadb/data:/var/lib/mysql"
    ports:
      - 3300:3300
    healthcheck:
      test: "/usr/bin/mysql --user=expressuser --password=expresspassword --execute \"SHOW DATABASES;\""
      interval: 1m
      timeout: 60s
      retries: 10
      start_period: 30s
  adminer:
    image: adminer
    ports:
      - 8080:8080