---
services:
  db:
    image: mariadb:11.2.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 20s
      retries: 10
  express:
    image: ghcr.io/alexispet/final-test-alice-aa-a/express:stable
    depends_on:
      - db
    #      build:
    #      context: .
    #      #      choose image : next
    #      target: express
    env_file: .env
    environment:
      NODE_ENV: stable
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
#    networks:
#      - custom_frontend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.next-prod.rule=Host(`ec2-44-202-87-3.compute-1.amazonaws.com`)"
      - "traefik.http.routers.next-prod.entrypoints=web"
#    command: ["npm", "run", "start"]
    volumes:
      - ".:/app"

  adminer:
    image: adminer
    ports:
      - 8081:8080

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable

#networks:
#  custom_frontend:
#    external: true