services:
  express:
    image: ghcr.io/alexispet/final-test-alice-aa-a/express:main
#      build:
#      context: .
#      #      choose image : next
#      target: express
    environment:
      #      stable or unstable
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
#     dev
      - "3000:3000"
#      - prod
#      - 80:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: ["npm", "run", "start"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ".:/app"
  db:
    image: mariadb:11.2.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock