services:
  express:
    build:
      context: .
      #      choose image : next
      target: express
    environment:
      #      stable or unstable
      NODE_ENV: development
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: express
      MYSQL_USER: express
      MYSQL_PASSWORD: express
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ".:/app"
    command: [ "npm", "run", "start" ]
  db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: express
      MYSQL_USER: express
      MYSQL_PASSWORD: express
    volumes:
      - "./docker/mariadb/data:/var/lib/mariadb"
    ports:
      - 3000:3306
    healthcheck:
      test: "/usr/bin/mysql --user=expressuser --password=expresspassword --execute \"SHOW DATABASES;\""
      interval: 15s
      timeout: 60s
      retries: 10
      start_period: 30s
  adminer:
    image: adminer
    ports:
      - 8080:8080