services:
  express:
    build:
      context: .
      #      choose image : next
      target: express
    environment:
      #      stable or unstable
      NODE_ENV: development
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: expressdb
      MYSQL_USER: expressuser
      MYSQL_PASSWORD: expresspassword
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ".:/app"
    command: [ "npm", "run", "start" ]
  db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: no
      MYSQL_DATABASE: cesi_tp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - "./docker/mariadb/data:/var/lib/mariadb"
    ports:
      - 3000:3300
    healthcheck:
      test: "/usr/bin/mysql --user=expressuser --password=expresspassword --execute \"SHOW DATABASES;\""
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  adminer:
    image: adminer
    ports:
      - 8080:8080