name: Lighthouse CI

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Audit URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        id: lighthouse
        with:
          urls: |
            https://ec2-44-204-232-48.compute-1.amazonaws.com
            https://ec2-35-172-134-44.compute-1.amazonaws.com
          temporaryPublicStorage: true
